// Participant colours are generated by the UI and sent to the API as #RRGGBB (PRD §3.4). Hue is random,
// saturation and lightness are kept in a band that reads as a border and a label on the dark theme.
const toHex = (value: number) =>
  Math.round(value * 255)
    .toString(16)
    .padStart(2, "0");

const hslToHex = (hue: number, saturation: number, lightness: number): string => {
  const s = saturation / 100;
  const l = lightness / 100;
  const chroma = (1 - Math.abs(2 * l - 1)) * s;
  const x = chroma * (1 - Math.abs(((hue / 60) % 2) - 1));
  const m = l - chroma / 2;

  const sector = Math.floor(hue / 60) % 6;
  const [r, g, b] = [
    [chroma, x, 0],
    [x, chroma, 0],
    [0, chroma, x],
    [0, x, chroma],
    [x, 0, chroma],
    [chroma, 0, x],
  ][sector];

  return `#${toHex(r + m)}${toHex(g + m)}${toHex(b + m)}`.toUpperCase();
};

export const randomHexColor = (): string => {
  const hue = Math.floor(Math.random() * 360);
  const saturation = 65 + Math.random() * 20;
  const lightness = 55 + Math.random() * 15;
  return hslToHex(hue, saturation, lightness);
};
